### ISSUE TITLE
setting the target temp on the thermostat CT80 B2 Rev v1.09

### ISSUE THREAD

**Issue by stevejbauer** [mhrivnak/radiotherm#12]
Currently, I have two of the radio thermostats, model CT80 B2 Rev v1.09.  When working with the thermostat via the api, I noticed I could set the target temp on the thermostat if I used a only a interger for the target temp.  If the temp was a floating point number (ie 72.3), the setting of the target temp would fail.  In addition to this, I noticed I could set the target temp to 72.5 via the library and the thermostat would target temp would be set to 72.  Is this normal behavior for the other models of the radio thermostat as well?

**Comment by craftyguy** [comment]
I don't see this on the CT80 B1 Rev v1.00. Do you still see this with the latest version of this library?

**Comment by craftyguy** [comment]
Since there hasn't been any response, I'm going to assume that either there is no interest or the issue does not occur anymore. If I am wrong, please re-open after testing with the latest version of this library!
