### ISSUE TITLE
Rolling Up PRs?

### ISSUE THREAD

**Issue by m00dawg** [mhrivnak/radiotherm#20]
There are now about 3 PRs related to updating some Radio Thermostat hardware revisions. These are impacting other projects, such as Home Assistant, and seem to be fairly trivial patches. Since one patch dates back to January, I wanted to see what the update process timeline is so I know when to expect to see some of these hit mainline?

**Comment by nathanaelhuffman** [comment]
I'm also interested in both a roll up of the PRs and and a new release on pypi, 1.2 is not current with master. Any possibility of rolling another pypi release with the above mentioned PRs?

**Comment by mhrivnak** [comment]
Done and done. 1.3 is live on pypi. Sorry for the delay! I apparently had notifications off and forgot all about this repo.
