### ISSUE TITLE
Handle the API transient error condition(-1)

### ISSUE THREAD

**Issue by tubaman** [mhrivnak/radiotherm#24]
The [API developer guide](https://lowpowerlab.com/downloads/RadioThermostat_CT50_Honeywell_Wifi_API_V1.3.pdf) in section 2.7.3 states that tmode and/or temp could return a -1 in the case of a transient error within the thermostat.  Today these values get returned as-is.  We should instead handle these by raising an exception.

**Comment by tubaman** [comment]
Here's a PR: https://github.com/mhrivnak/radiotherm/pull/25

**Comment by tubaman** [comment]
Note: I've seen these transient errors in the field via home assistant.

**Comment by tubaman** [comment]
@mhrivnak, any thoughts on this?

**Comment by craftyguy** [comment]
According to @TD22057's comment on that PR, this may cause issues for home assistant, since they apparently rely on this library returning -1 when there are issues.

**Comment by craftyguy** [comment]
The relevant PR has been merged, I will submit changes for homeassistant when I make a new release here.
