### ISSUE TITLE
Radio Thermostat CT80 Rev B1 V1.00 error

### ISSUE THREAD

**Issue by AmpacheUser** [mhrivnak/radiotherm#26]
I get the following error when trying to set up a CT80 Rev B1 V1.00 Radio Thermostat in Home Assistant:

ERROR:homeassistant.components.climate:Error while setting up platform radiotherm
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 164, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 393, in wait_for
    return fut.result()
  File "/usr/lib64/python3.4/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.4/site-packages/homeassistant/components/climate/radiotherm.py", line 66, in setup_platform
    tstats.append(RadioThermostat(tstat, hold_temp, away_temps))
  File "/usr/lib/python3.4/site-packages/homeassistant/components/climate/radiotherm.py", line 80, in __init__
    self.set_time()
  File "/usr/lib/python3.4/site-packages/homeassistant/components/climate/radiotherm.py", line 216, in set_time
    'minute': now.minute
AttributeError: 'NoneType' object has no attribute 'time'

It looks like I have a different version of the CT80 that I have not seen before.
Anything you need to help assist in resolving this, please let me know.

**Comment by AmpacheUser** [comment]
I went ahead and added the Model to the thermostat.py and __init__.py files but the error still comes up.

**Comment by AmpacheUser** [comment]
After running the following script:

`import radiotherm

try:
    tstat = radiotherm.get_thermostat("192.168.4.75")
    print ("Test 1: " + str(tstat))
    print (tstat.temp['raw'])
except Exception as e:
    print (e)
    pass

try:
    tstat =  radiotherm.thermostat("192.168.4.75")
    print (object)
    print ("Test 2: " + str(tstat))
    print (tstat.temp['raw'])
except Exception as e:
    print (e)
    pass

try:
    tstat = radiotherm.thermostat.CT80("192.168.4.75")
    print ("Test 3: " + str(tstat))
    print (tstat.temp['raw'])
except Exception as e:
    print (e)
    pass
	
try:
    tstat = radiotherm.thermostat.CT80RevB("192.168.4.75")
    print ("Test 4: " + str(tstat))
    print (tstat.temp['raw'])
except Exception as e:
    print (e)
    pass`

This is the output:

`Test 1: <radiotherm.thermostat.CT80RevB1v100 object at 0x7fca84286c88>
79.5
'module' object is not callable
Test 3: <radiotherm.thermostat.CT80 object at 0x7fca8432af98>
79.5
Test 4: <radiotherm.thermostat.CT80RevB object at 0x7fca84286c88>
79.0
`

I hope this helps.

**Comment by craftyguy** [comment]
This should be resolved now. Closing issue, but please re-open if someone continues to experience this after testing the latest in master branch.
