### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by craftyguy** [mhrivnak/radiotherm#31]
Just curious, because some projects (like home-assistant) use this project to add support for radiotherm devices, and if this project is no longer being maintained then we should fork this and maintain it so that support for newer devices can be added and issues resolved.

**Comment by craftyguy** [comment]
@mhrivnak great! I'm not affiliated with home-assistant, but actively use this project through home-assistant. I'd be willing to help review/merge PRs and fix issues! I don't know if the HA folks would be willing to maintain it, but I can post something on their forum in the meantime.

**Comment by craftyguy** [comment]
I posted this question to the HA dev discord chat, the only response was that they prefered someone else maintain it externally.

**Comment by craftyguy** [comment]
@mhrivnak if you are still interested in having more maintainers, I'd like to volunteer!

**Comment by TD22057** [comment]
I'd be willing to help as well.  Keeping this alive for use in Home Assistant is really important to me.

**Comment by mhrivnak** [comment]
Great! The best way to get started is to review some open PRs. Even just having a comment that says LGTM can be helpful.

**Comment by craftyguy** [comment]
@mhrivnak 

Sure! I'll look over the open PRs and test/comment. I've already done a handful so far.

One thing that would make it much easier is if I were added to the project as a contributor (or whatever the right permission level is), so I can 'review' PRs and comment on lines. Currently I cannot do this, so I have to explain/ask questions in a general comment to the PR. I don't need merge rights or anything :)

**Comment by TD22057** [comment]
@mhrivnak Any chance you can merge some of the PR's any time soon?

**Comment by craftyguy** [comment]
Or if you don't have time, designate someone with merge permissions who can help with maintaining this project so our thermostats continue to work well? :)

**Comment by mhrivnak** [comment]
@craftyguy I just added you as a collaborator. If you can take care of getting things merged within the bounds of semantic versioning (semver.org), that would be fantastic.

**Comment by craftyguy** [comment]
@mhrivnak awesome, thank you! I'll review semver.org to make sure I didn't forget anything and start merging!
