### ISSUE TITLE
Migrate to gitlab

### ISSUE THREAD

**Issue by craftyguy** [mhrivnak/radiotherm#36]
I light of recent news about Microsoft acquiring Github, I propose that this project be moved to Gitlab.com. I am in the process of migrating my projects now, and it seems that since I have contributor rights here I am able to migrate this project too. @mhrivnak, thoughts?

**Comment by TD22057** [comment]
Why?  It was just announced and nothing has changed.  If you know of some policy change that github is going to make because of this then bring it up.  Changing just because someone buys them makes no sense to me.

**Comment by mhrivnak** [comment]
I understand and respect that some people have strong feelings about Microsoft acquiring GitHub. I happen to not be one of them. I don't mind elaborating on why, but it probably doesn't matter for these purposes.

Looking at it pragmatically, I expect that GitHub will continue to be the largest home for open source projects and contributors by a wide margin. Hosting a project on GitHub reduces friction for new contributors; it's familiar, it's the default place where people look for existing projects, almost everyone already has an account, and most know the fork+PR workflow like the back of their hand. The OSS community at large is concentrated here, and while I know some will leave, I don't expect the tide to shift.

If I'm wrong and the tide does shift, I'm very happy to look at other options like GitLab. Or if this acquisition results in undesirable changes to what GitHub is offering, I'm happy to move.

For now, GitHub provides a great service for free and has by far the biggest community. I'll leave this issue open for a bit in the spirit of inviting discussion, but I do not plan to move any repositories.

**Comment by craftyguy** [comment]
Fair enough. I feel differently, and will be removing my github account once I have migrated away all of my repos. 

@mhrivnak Since this project is practically not being maintained by you, and I'm willing to keep it going, I thought I would offer to do that, but it would not be here on github if I do.

> Changing just because someone buys them makes no sense to me.

Well, it's not *just* anyone, it's the company that spent decades trying to kill open source software, the company responsible for E3 (embrace, extend, extinguish). But hey, things will be different now, right? "Don't worry about the past, you can trust us now" -- Microsoft
