### ISSUE TITLE
Need new maintainer for PyPI

### ISSUE THREAD

**Issue by craftyguy** [mhrivnak/radiotherm#40]
@mhrivnak 

Some applications that use this library (e.g. Home Assistant) use pip to install radiotherm, and currently it's serving an older version (1.3): https://pypi.org/project/radiotherm/

Can you please consider adding a new co-maintainer on PyPI to make sure it's up to date with the latest releases of this library? [I volunteer](https://pypi.org/user/craftyguy/) to do that if you don't have anyone else in mind!

**Comment by craftyguy** [comment]
@mhrivnak any thoughts?

**Comment by mhrivnak** [comment]
I'm happy to add you. Right now when I try, pypi is giving me a 503 error with their "Sorry, something went wrong" page. Their status page doesn't indicate any problems though. Not sure what to make of that.

**Comment by mhrivnak** [comment]
I filed a bug report: https://github.com/pypa/warehouse/issues/4496

**Comment by craftyguy** [comment]
wow, bad timing with pypi.. Anyways, thanks for updating it in the repo! :smile:

**Comment by mhrivnak** [comment]
Success! They fixed the pypi bug, and I was able to add you as a maintainer.

**Comment by craftyguy** [comment]
Thanks, very much appreciated!
