### ISSUE TITLE
Connect a Python Script to IFTTT?

### ISSUE THREAD

**Issue by scottfree1** [mhrivnak/radiotherm#45]
Anyone up for giving this a shot?  Personally I'm not very familiar with python/IFTTT but this seems like this should be pretty straight forward  for someone who knows what they are doing 

https://medium.com/mai-piu-senza/connect-a-python-script-to-ifttt-8ee0240bb3aa

**Comment by craftyguy** [comment]
I have no idea about IFTTT (booo proprietary platforms, but I digress), but I and a few others use this library as a part of [Home Assistant](https://home-assistant.io), which offers 'if this then that' automation.

In any case, unless you are reporting a specific problem with this library or a feature request, what you are asking is outside the scope of this project so I will close this issue :)

**Comment by scottfree1** [comment]
I've been trying to get my ct30 working with first alexa, but dumped alexa to unreliable lots of "red rings".
Google home is less extensible but more reliable. 

Since the ct30 has a web ui It seems it should have a cmd for =/-1 degree (all I really want to do) 

Something  like this url that pans my security cam by 5 degrees??
http://ipadd/decoder_control.cgi?command=4&onestep=1&degree=5&user=admin&pwd=xxx&url=next

**Comment by scottfree1** [comment]
"In any case, unless you are reporting a specific problem with this library or a feature request, what you are asking is outside the scope of this project so I will close this issue :)"

If the title was "radiotherm integration with Google home/assistant/voice " is that scope-able?

**Comment by craftyguy** [comment]
Are you reporting a specific issue with the library or requesting some new feature beyond "help me get it working with XYZ service? If the answer is yes, feel free to re-open this issue and provide specifics :smile:
