### ISSUE TITLE
Unable to maintain project going forward

### ISSUE THREAD

**Issue by craftyguy** [mhrivnak/radiotherm#46]
@mhrivnak 

I've given up on these devices, they're just too unreliable to use for home automation for me (no fault of this project), but as a consequence I no longer have a way to test merge requests, etc. Thank you for letting me carry the torch for a while. Hopefully someone else (with trusted contributions here already?) is able to step up.

**Comment by mhrivnak** [comment]
Thank you for taking the lead on this for so long!

**Comment by vinnyfuria** [comment]
@mhrivnak @craftyguy I'd be happy to take over maintenance of this library. I'm motivated by #47 and to get solid home assistant support working.
